// Code generated by "stringer -type=ScheduleType -trimprefix Schedule"; DO NOT EDIT.

package checron

import "strconv"

const _ScheduleType_name = "MinuteHourDayMonthDayOfWeek"

var _ScheduleType_index = [...]uint8{0, 6, 10, 13, 18, 27}

func (i ScheduleType) String() string {
	if i < 0 || i >= ScheduleType(len(_ScheduleType_index)-1) {
		return "ScheduleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScheduleType_name[_ScheduleType_index[i]:_ScheduleType_index[i+1]]
}
