// Code generated by "stringer -type=scheduleType -trimprefix Schedule"; DO NOT EDIT.

package crontabparser

import "strconv"

const _scheduleType_name = "scheduleMinutescheduleHourscheduleDayscheduleMonthscheduleDayOfWeek"

var _scheduleType_index = [...]uint8{0, 14, 26, 37, 50, 67}

func (i scheduleType) String() string {
	if i < 0 || i >= scheduleType(len(_scheduleType_index)-1) {
		return "scheduleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _scheduleType_name[_scheduleType_index[i]:_scheduleType_index[i+1]]
}
